site_name: 我的文档
theme:
  name: material
  # custom_dir: overrides
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  palette: 
    - scheme: default
      toggle:
        icon: material/lightbulb
        name: 关灯
      primary: cyan
      accent: cyan
    - scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: 开灯
      primary: indigo
      accent: indigo
  language: zh
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
extra_css:
  - assets/stylesheets/extra.css
extra:
  generator: true
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/ra1nma1n
plugins:
    - glightbox:
       touchNavigation: true
       loop: false
       effect: zoom
       width: 100%
       height: auto
       zoomable: true
       draggable: true
    - search:
        lang:
          - en
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      # options:
      #   custom_icons:
      #     - overrides/.icons
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
nav:
  - 学习笔记:
    - notes/index.md
    - linux文件与权限: notes/09-Sep-22.md
    - linux文件结构与FHS: notes/12-Sep-22.md
    - 常用命令查漏补缺: notes/14-Sep-22.md
    - linux文件系统与磁盘, 软连接与硬连接: notes/15-Sep-22.md
  - 上网冲浪:
    - surf-the-internet/index.md
    - 代理，互联网的第一步: surf-the-internet/HowToProxy.md
    - 开始使用linux啦: surf-the-internet/StartWithLinux.md
    - ubuntu美化及踩坑: surf-the-internet/GnomeShellStuffs.md
    - 修改Telegram字体: surf-the-internet/TelegramFont.md