/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/GTNH-list': RouteRecordInfo<'/posts/GTNH-list', '/posts/GTNH-list', Record<never, never>, Record<never, never>>,
    '/posts/java-mapperInterface': RouteRecordInfo<'/posts/java-mapperInterface', '/posts/java-mapperInterface', Record<never, never>, Record<never, never>>,
    '/posts/java-stream-style': RouteRecordInfo<'/posts/java-stream-style', '/posts/java-stream-style', Record<never, never>, Record<never, never>>,
    '/posts/misc-010625': RouteRecordInfo<'/posts/misc-010625', '/posts/misc-010625', Record<never, never>, Record<never, never>>,
    '/posts/smart-contract': RouteRecordInfo<'/posts/smart-contract', '/posts/smart-contract', Record<never, never>, Record<never, never>>,
    '/posts/transaction': RouteRecordInfo<'/posts/transaction', '/posts/transaction', Record<never, never>, Record<never, never>>,
    '/posts/tweaking-arch/': RouteRecordInfo<'/posts/tweaking-arch/', '/posts/tweaking-arch', Record<never, never>, Record<never, never>>,
    '/posts/web3j-collector': RouteRecordInfo<'/posts/web3j-collector', '/posts/web3j-collector', Record<never, never>, Record<never, never>>,
    '/posts/web3j-mnemonic': RouteRecordInfo<'/posts/web3j-mnemonic', '/posts/web3j-mnemonic', Record<never, never>, Record<never, never>>,
    '/posts/web3j-transfer-eth': RouteRecordInfo<'/posts/web3j-transfer-eth', '/posts/web3j-transfer-eth', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
